### ISSUE TITLE
queue simple / queue tree

### ISSUE THREAD

**Issue by lzahradil** [MadaMzandu/uisp-ros-plugin#11]
Please add queue simple / queue tree with client agregated group include burst

As the setting of the uisp service plan allows

**Comment by MadaMzandu** [comment]
Thanks will look at including burst in the next release

**Comment by MadaMzandu** [comment]
The main difference that I see between ubiquiti aggregation and the plugin contention ratios is that the ubiquiti version adjusts the client queues to fit the parent, while the contention ratio adjusts the parent to fit the clients. In this I think the contention ratio is better because the customer's service limits do not vary with volume thus offering a more consistent service. I would like more input on this one if I am to consider implementing this as a feature.

**Comment by kikipatton** [comment]
Trying to upload the zip, but uisp returns "Plugin manifest could not be found in the ZIP archive."

**Comment by MadaMzandu** [comment]
Please verify the correct zip is downloaded. It should be the one in the src/ directory link below.

https://github.com/MadaMzandu/uisp-ros-plugin/blob/main/src/ros-plugin.zip

**Comment by alvianx** [comment]
> The main difference that I see between ubiquiti aggregation and the plugin contention ratios is that the ubiquiti version adjusts the client queues to fit the parent, while the contention ratio adjusts the parent to fit the clients. In this I think the contention ratio is better because the customer's service limits do not vary with volume thus offering a more consistent service. I would like more input on this one if I am to consider implementing this as a feature.

I think aggregation & contention ratio is the same concept to guaranteed speed limit, so either way should work.

Also aggregation seems more flexible, you just need to add the "parent limit" speed (and maybe burst) then count how much max client that can be connected to service plan on the plugin UI or automatically set based on how much client that connected.

For reference on aggregation: https://help.ui.com/hc/en-us/articles/360023971673-UNMS-v1-Suspension-and-Traffic-Shaping#3

**Comment by MadaMzandu** [comment]
Thanks for the reference, I will look at it and let you know
