### ISSUE TITLE
Lastest version not connecting to mikrotik routers

### ISSUE THREAD

**Issue by afrietaadmin** [MadaMzandu/uisp-ros-plugin#53]
HI Mada,

Am running UISP 2.3.39, upgraded from 1.8.xxx to 2.0.2.11  I have disabled the webhook to localhost. The plugin does not connect to mikrotik routers (ver 7.41) as I cannot see that the accounts created for the plugging are logging in, even when doing a sync or rebuild. After installing and doing a rebuild user accounts on all devices were 0. 

Uninstalled and reinstalled, same behaviour. I am also unable to change the setting, "disable bandwidth contention" - it stays ticked.

Any assistance would be appreciated.

regards
Shahin

**Comment by MadaMzandu** [comment]
Hi,
Thanks for the feedback. Try https://github.com/MadaMzandu/uisp-ros-plugin/releases/tag/2.0.2.11-debug. Install do a fresh install, enable debug in the settings, then upload your 1.8.x backup. Verify that devices and settings are restored. And review debug logs in ucrm > settings > plugin. If you have to post the debug here pls make sure that sensitive information is edited from the paste.

1. disabling the webhook will also disable real time mikrotik updates, but features like rebuild should still work
2. the parent queues are being phased out because they limit the plugin to 128 customers per service plan. This is an HTB limitation which mikrotik has inherited. Instead bursting has been introduced for better qos tuning. However if parent queues are enabled in your 1.8.x backup the plugin will continue to manage the parents
Thanks

**Comment by MadaMzandu** [comment]
Hi Shahin,

Have you made any progress?

**Comment by afrietaadmin** [comment]
Hi Mada,

Thanks its working, I have the standard API enabled, when I looked at the
documentation I saw you making use of the REST API.

Its working now thanks

Appreciate everything
Regards
Shahin
