### ISSUE TITLE
use of domain name

### ISSUE THREAD

**Issue by MetallicJohn** [MadaMzandu/uisp-ros-plugin#59]
i have tunnelled access to mikrotik and i can access the webfig on a domain name. if i use the domain name it doesnt connect to my mikrotik. whats the correct way to use a domain name instead of IP?

**Comment by MadaMzandu** [comment]
Technically if you are able to resolve the domain name and can ping the same from the uisp server's command line then it should be able to manage the mikrotik through a tunnel or otherwise.

 If you can resolve and ping then you might have a firewall rule on tcp 8728 or an access list on ip > services > api. If you cannot resolve then that's probably dns and if you cannot ping then thats probably routing.

**Comment by kikipatton** [comment]
If you need support @MetallicJohn , I'll be glad to assist you. From the ros plugin, does it show a green arrow pointing up?

**Comment by MetallicJohn** [comment]
from the plugin i do not see a green arrow. a subdomain should work okay? I can resolve and also ping from the server

**Comment by MetallicJohn** [comment]
actually the hostname is not accepted in the input field. error:check input value

**Comment by MadaMzandu** [comment]
sound like a bug with the verification, will check and update

**Comment by MadaMzandu** [comment]
This has been fixed in 2.0.2.14. Please test and close issue if works

**Comment by MetallicJohn** [comment]
i have tested the domain name validation and its accepting
